name: "CI"

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Nuget package version'     
        required: false
        default: '1.0.0'

env:
  PROJECT_PATH: 'Artnix.Scheduler.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
        
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Pack command'
      id: pack-command
      run: echo "::set-output name=PARAMS::--no-restore --no-build --configuration Release -p:PackageVersion=${{ github.event.inputs.packageVersion }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}"

    - name: 'Pack project Artnix.Scheduler'
      run: |
        dotnet pack 'src/Artnix.Scheduler/Artnix.Scheduler.csproj' ${{ steps.pack-command.outputs.PARAMS }}
        dotnet pack 'src/Artnix.Scheduler.DependencyInjection/Artnix.Scheduler.DependencyInjection.csproj' ${{ steps.pack-command.outputs.PARAMS }}
      
    - name: Archive NuGet Package Artnix.Scheduler
      uses: actions/upload-artifact@v1
      with:
        name: Pack GitActionsTestApp
        path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/

    - name: 'Push command'
      id: push-command
      run: echo "::set-output name=PARAMS::--api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source ${{ env.NUGET_SOURCE_URL }}"
      
    - name: Push to NuGet
      run: |
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/Artnix.SchedulerFramework.${{ github.event.inputs.packageVersion }}.nupkg ${{ steps.push-command.outputs.PARAMS }}
        dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/Artnix.SchedulerFramework.DependencyInjection.${{ github.event.inputs.packageVersion }}.nupkg ${{ steps.push-command.outputs.PARAMS }}
